# CS 513 C - Knowledge Discovery and Data Mining Project

**Problem Definition: Algorithm Performance Analysis for Diabetes Classification**

**Objective:** The primary goal is to analyze and compare the performance of various machine learning algorithms in accurately classifying individuals into categories such as diabetic or non-diabetic. This involves understanding and quantifying how effectively each algorithm can handle the data provided, make predictions, and how their predictions align with actual clinical diagnoses.

In [37]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt

In [38]:
df = pd.read_csv("C:\\Users\Vanshika\Downloads\projects\diabetes_binary_health_indicators_BRFSS2015.csv")

## Step 1: Exploratory Data Analysis 
Data Understanding and Quality Checks

In [39]:
df.head() #Initial Inspection, essential to understand how the data is structured, including column names and row indices.

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        1.0  30.0     0.0     0.0   
1              0.0     1.0       1.0        1.0  34.0     1.0     0.0   
2              0.0     0.0       0.0        1.0  18.0     0.0     0.0   
3              0.0     1.0       1.0        1.0  28.0     0.0     0.0   
4              0.0     0.0       0.0        0.0  20.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           1.0     1.0  ...            1.0   
1                   0.0           0.0     1.0  ...            1.0   
2                   0.0           0.0     0.0  ...            1.0   
3                   1.0           0.0     0.0  ...            1.0   
4                   0.0           1.0     1.0  ...            0.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      3.0       0.0       2.0       1.0  0.0  10.0        4.0   
1          0.0      4.0       0.0       0.0       1.0  0.0  11.0        5.0   
2          0.0      1.0       1.0       0.0       0.0  1.0   1.0        5.0   
3          0.0      2.0       0.0       0.0       1.0  0.0  12.0        4.0   
4          0.0      1.0       0.0       0.0       0.0  0.0   7.0        5.0   

   Income  
0     1.0  
1     8.0  
2     1.0  
3     4.0  
4     6.0  

[5 rows x 22 columns]

In [40]:
df.shape #helps in understanding data dimensions, validation, quality, memory and performance consideration. 

(5000, 22)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Diabetes_binary       5000 non-null   float64
 1   HighBP                5000 non-null   float64
 2   HighChol              5000 non-null   float64
 3   CholCheck             5000 non-null   float64
 4   BMI                   5000 non-null   float64
 5   Smoker                5000 non-null   float64
 6   Stroke                5000 non-null   float64
 7   HeartDiseaseorAttack  5000 non-null   float64
 8   PhysActivity          5000 non-null   float64
 9   Fruits                5000 non-null   float64
 10  Veggies               5000 non-null   float64
 11  HvyAlcoholConsump     5000 non-null   float64
 12  AnyHealthcare         5000 non-null   float64
 13  NoDocbcCost           5000 non-null   float64
 14  GenHlth               5000 non-null   float64
 15  MentHlth             

In [42]:
df.describe()

Diabetes_binary       HighBP     HighChol    CholCheck          BMI  \
count      5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean          0.137800     0.435800     0.426800     0.962000    28.451400   
std           0.344724     0.495911     0.494662     0.191215     6.573757   
min           0.000000     0.000000     0.000000     0.000000    15.000000   
25%           0.000000     0.000000     0.000000     1.000000    24.000000   
50%           0.000000     0.000000     0.000000     1.000000    27.000000   
75%           0.000000     1.000000     1.000000     1.000000    31.000000   
max           1.000000     1.000000     1.000000     1.000000    87.000000   

            Smoker       Stroke  HeartDiseaseorAttack  PhysActivity  \
count  5000.000000  5000.000000           5000.000000    5000.00000   
mean      0.445200     0.038600              0.089000       0.73840   
std       0.497038     0.192659              0.284772       0.43955   
min       0.000000     0.000000              0.000000       0.00000   
25%       0.000000     0.000000              0.000000       0.00000   
50%       0.000000     0.000000              0.000000       1.00000   
75%       1.000000     0.000000              0.000000       1.00000   
max       1.000000     1.000000              1.000000       1.00000   

            Fruits  ...  AnyHealthcare  NoDocbcCost      GenHlth    MentHlth  \
count  5000.000000  ...    5000.000000  5000.000000  5000.000000  5000.00000   
mean      0.629200  ...       0.947800     0.087400     2.533200     3.12700   
std       0.483067  ...       0.222452     0.282449     1.068984     7.28315   
min       0.000000  ...       0.000000     0.000000     1.000000     0.00000   
25%       0.000000  ...       1.000000     0.000000     2.000000     0.00000   
50%       1.000000  ...       1.000000     0.000000     2.000000     0.00000   
75%       1.000000  ...       1.000000     0.000000     3.000000     2.00000   
max       1.000000  ...       1.000000     1.000000     5.000000    30.00000   

          PhysHlth     DiffWalk          Sex         Age    Education  \
count  5000.000000  5000.000000  5000.000000  5000.00000  5000.000000   
mean      4.335600     0.172200     0.439000     8.02560     5.026400   
std       8.756478     0.377592     0.496315     3.06033     0.983411   
min       0.000000     0.000000     0.000000     1.00000     1.000000   
25%       0.000000     0.000000     0.000000     6.00000     4.000000   
50%       0.000000     0.000000     0.000000     8.00000     5.000000   
75%       3.000000     0.000000     1.000000    10.00000     6.000000   
max      30.000000     1.000000     1.000000    13.00000     6.000000   

            Income  
count  5000.000000  
mean      6.034200  
std       2.056666  
min       1.000000  
25%       5.000000  
50%       7.000000  
75%       8.000000  
max       8.000000  

[8 rows x 22 columns]

In [43]:
df.sample(20)

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
4120              0.0     1.0       1.0        1.0  34.0     1.0     0.0   
2293              0.0     0.0       0.0        1.0  25.0     0.0     0.0   
99                0.0     0.0       0.0        1.0  33.0     1.0     0.0   
2986              0.0     0.0       1.0        1.0  31.0     1.0     0.0   
477               0.0     0.0       0.0        1.0  31.0     0.0     0.0   
2925              0.0     1.0       0.0        1.0  34.0     1.0     0.0   
3819              0.0     1.0       0.0        1.0  27.0     1.0     0.0   
459               0.0     0.0       0.0        1.0  26.0     0.0     0.0   
4710              1.0     1.0       1.0        1.0  37.0     0.0     0.0   
1786              0.0     0.0       1.0        1.0  39.0     0.0     0.0   
3631              0.0     0.0       0.0        1.0  28.0     1.0     0.0   
4175              0.0     1.0       0.0        1.0  27.0     1.0     0.0   
2714              0.0     1.0       0.0        1.0  30.0     0.0     0.0   
995               1.0     1.0       1.0        1.0  25.0     1.0     0.0   
2682              0.0     0.0       1.0        1.0  25.0     1.0     0.0   
4448              1.0     1.0       1.0        1.0  28.0     0.0     1.0   
2412              1.0     1.0       1.0        1.0  40.0     0.0     0.0   
1445              0.0     1.0       1.0        1.0  58.0     0.0     0.0   
3937              1.0     1.0       0.0        1.0  31.0     0.0     0.0   
51                0.0     0.0       0.0        1.0  23.0     1.0     0.0   

      HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
4120                   1.0           1.0     0.0  ...            1.0   
2293                   0.0           0.0     1.0  ...            1.0   
99                     0.0           1.0     1.0  ...            1.0   
2986                   0.0           1.0     1.0  ...            1.0   
477                    0.0           1.0     1.0  ...            1.0   
2925                   0.0           1.0     1.0  ...            1.0   
3819                   0.0           1.0     1.0  ...            1.0   
459                    0.0           1.0     1.0  ...            1.0   
4710                   0.0           1.0     1.0  ...            1.0   
1786                   0.0           1.0     1.0  ...            1.0   
3631                   0.0           1.0     1.0  ...            1.0   
4175                   0.0           0.0     1.0  ...            1.0   
2714                   0.0           1.0     0.0  ...            1.0   
995                    0.0           1.0     1.0  ...            1.0   
2682                   0.0           1.0     0.0  ...            1.0   
4448                   0.0           1.0     1.0  ...            1.0   
2412                   0.0           0.0     1.0  ...            1.0   
1445                   1.0           0.0     1.0  ...            1.0   
3937                   1.0           0.0     1.0  ...            1.0   
51                     0.0           1.0     1.0  ...            1.0   

      NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
4120          0.0      4.0       0.0       0.0       0.0  0.0  12.0   
2293          0.0      2.0       0.0       0.0       0.0  0.0   8.0   
99            0.0      2.0       0.0      10.0       0.0  0.0   4.0   
2986          0.0      2.0       0.0       0.0       0.0  0.0  11.0   
477           0.0      2.0       0.0       0.0       0.0  0.0  13.0   
2925          0.0      2.0       0.0       0.0       0.0  0.0   7.0   
3819          0.0      3.0       0.0       0.0       0.0  0.0  10.0   
459           0.0      1.0       0.0       0.0       0.0  1.0  11.0   
4710          0.0      4.0      30.0       0.0       0.0  0.0   3.0   
1786          0.0      4.0       0.0       2.0       0.0  0.0   6.0   
3631          0.0      2.0       2.0       0.0       1.0  0.0  13.0   
4175          0.0      4.0       0.0       0

In [44]:
df.isnull().sum() #Checking for the duplicates in the features

Diabetes_binary         0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [45]:
x = df.drop(['Diabetes_binary'], axis = 1)
y = df['Diabetes_binary']

In [46]:
pip install scikit-learn --upgrade

Note: you may need to restart the kernel to use updated packages.


In [47]:
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

# Naive Bayes

In [48]:

from sklearn.naive_bayes import GaussianNB


# Create a Naive Bayes classifier
classifier = GaussianNB()

# Train the classifier on the training data
classifier.fit(x_train, y_train)

# Make predictions on the testing data
y_pred = classifier.predict(x_test)

# Compute confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()


# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Compute precision
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Compute specificity
specificity = tn / (tn + fp)
print('Specificity:', specificity)


# Compute recall
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Compute sensitivity
sensitivity= tp / (tp + fn)
print('Sensitivity:', sensitivity)

# Compute F1-score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

print(y_pred)
print(y_test)

Accuracy: 0.7673333333333333
Precision: 0.33064516129032256
Specificity: 0.8050117462803446
Recall: 0.5515695067264574
Sensitivity: 0.5515695067264574
F1 Score: 0.41344537815126053
              precision    recall  f1-score   support

         0.0       0.91      0.81      0.85      1277
         1.0       0.33      0.55      0.41       223

    accuracy                           0.77      1500
   macro avg       0.62      0.68      0.63      1500
weighted avg       0.83      0.77      0.79      1500

[[1028  249]
 [ 100  123]]
[0. 0. 0. ... 0. 0. 0.]
398     0.0
3833    0.0
4836    0.0
4572    0.0
636     0.0
       ... 
4554    0.0
4807    0.0
1073    0.0
2906    0.0
1357    0.0
Name: Diabetes_binary, Length: 1500, dtype: float64


# K-Nearest Neighbour

In [49]:
from sklearn.neighbors import KNeighborsClassifier


In [50]:

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)


# Compute confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print("Knn Output")

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Compute precision
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Compute specificity
specificity = tn / (tn + fp)
print('Specificity:', specificity)

# Compute recall
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Compute sensitivity
sensitivity= tp / (tp + fn)
print('Sensitivity:', sensitivity)

# Compute F1-score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))



Knn Output
Accuracy: 0.828
Precision: 0.3643410852713178
Specificity: 0.9357870007830854
Recall: 0.21076233183856502
Sensitivity: 0.21076233183856502
F1 Score: 0.26704545454545453
              precision    recall  f1-score   support

         0.0       0.87      0.94      0.90      1277
         1.0       0.36      0.21      0.27       223

    accuracy                           0.83      1500
   macro avg       0.62      0.57      0.58      1500
weighted avg       0.80      0.83      0.81      1500

[[1195   82]
 [ 176   47]]


# CART


In [51]:
from sklearn.tree import DecisionTreeClassifier


CART = DecisionTreeClassifier()

CART.fit(x_train, y_train)
y_pred = CART.predict(x_test)
# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Compute precision
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Compute specificity
specificity = tn / (tn + fp)
print('Specificity:', specificity)

# Compute recall
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Compute sensitivity
sensitivity= tp / (tp + fn)
print('Sensitivity:', sensitivity)

# Compute F1-score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))



Accuracy: 0.7966666666666666
Precision: 0.3305785123966942
Specificity: 0.9357870007830854
Recall: 0.35874439461883406
Sensitivity: 0.21076233183856502
F1 Score: 0.34408602150537637
              precision    recall  f1-score   support

         0.0       0.89      0.87      0.88      1277
         1.0       0.33      0.36      0.34       223

    accuracy                           0.80      1500
   macro avg       0.61      0.62      0.61      1500
weighted avg       0.80      0.80      0.80      1500

[[1115  162]
 [ 143   80]]


# Decision Tree

In [52]:


from sklearn.tree import DecisionTreeClassifier

DecisionTree = DecisionTreeClassifier(max_depth = 6)
DecisionTree.fit(x_train,y_train)
y_pred = DecisionTree.predict(x_test)

# Compute confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print(" Decision Tree Output")

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Compute precision
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Compute specificity
specificity = tn / (tn + fp)
print('Specificity:', specificity)

# Compute recall
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Compute sensitivity
sensitivity= tp / (tp + fn)
print('Sensitivity:', sensitivity)

# Compute F1-score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))


 Decision Tree Output
Accuracy: 0.8486666666666667
Precision: 0.4838709677419355
Specificity: 0.9498825371965545
Recall: 0.26905829596412556
Sensitivity: 0.26905829596412556
F1 Score: 0.345821325648415
              precision    recall  f1-score   support

         0.0       0.88      0.95      0.91      1277
         1.0       0.48      0.27      0.35       223

    accuracy                           0.85      1500
   macro avg       0.68      0.61      0.63      1500
weighted avg       0.82      0.85      0.83      1500

[[1213   64]
 [ 163   60]]


# Random Forest

In [53]:
from sklearn.ensemble import RandomForestClassifier

Random_forest = RandomForestClassifier()
Random_forest.fit(x_train,y_train)
y_pred = Random_forest.predict(x_test)
#classification_report(y_test,y_pred)

# Compute confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print("Output Random Forest")

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Compute precision
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Compute specificity
specificity = tn / (tn + fp)
print('Specificity:', specificity)


# Compute recall
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Compute sensitivity
sensitivity= tp / (tp + fn)
print('Sensitivity:', sensitivity)

# Compute F1-score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)


print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))



Output Random Forest
Accuracy: 0.86
Precision: 0.6140350877192983
Specificity: 0.9827721221613156
Recall: 0.15695067264573992
Sensitivity: 0.15695067264573992
F1 Score: 0.25
              precision    recall  f1-score   support

         0.0       0.87      0.98      0.92      1277
         1.0       0.61      0.16      0.25       223

    accuracy                           0.86      1500
   macro avg       0.74      0.57      0.59      1500
weighted avg       0.83      0.86      0.82      1500

[[1255   22]
 [ 188   35]]


# C_50

In [54]:
import seaborn as sns
from sklearn.tree import plot_tree


model = DecisionTreeClassifier(criterion='entropy', max_depth=3,splitter='best',max_leaf_nodes=5)
model.fit(x_train,y_train)
target_pred = model.predict(x_test)

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Compute precision
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Compute specificity
specificity = tn / (tn + fp)
print('Specificity:', specificity)


# Compute recall
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Compute sensitivity
sensitivity= tp / (tp + fn)
print('Sensitivity:', sensitivity)

# Compute F1-score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)
print(f"\n Classification Report:")
print(classification_report(y_test,y_pred))

plt.figure(figsize=(50,30), dpi=250)
plot_tree(model,fontsize=20,filled=True,feature_names=x.columns);

Accuracy: 0.86
Precision: 0.6140350877192983
Specificity: 0.9827721221613156
Recall: 0.15695067264573992
Sensitivity: 0.15695067264573992
F1 Score: 0.25

 Classification Report:
              precision    recall  f1-score   support

         0.0       0.87      0.98      0.92      1277
         1.0       0.61      0.16      0.25       223

    accuracy                           0.86      1500
   macro avg       0.74      0.57      0.59      1500
weighted avg       0.83      0.86      0.82      1500



# Support Vector Machine

In [55]:

from sklearn.svm import SVC


svm = SVC(gamma = 'auto')
svm.fit(x_train,y_train)
y_pred = svm.predict(x_test)


# Compute confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print("Support Vector Machines (SVM) Output")

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Compute precision
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Compute specificity
specificity = tn / (tn + fp)
print('Specificity:', specificity)

# Compute recall
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Compute sensitivity
sensitivity= tp / (tp + fn)
print('Sensitivity:', sensitivity)

# Compute F1-score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))



Support Vector Machines (SVM) Output
Accuracy: 0.8493333333333334
Precision: 0.4444444444444444
Specificity: 0.9882537196554424
Recall: 0.053811659192825115
Sensitivity: 0.053811659192825115
F1 Score: 0.09600000000000002
              precision    recall  f1-score   support

         0.0       0.86      0.99      0.92      1277
         1.0       0.44      0.05      0.10       223

    accuracy                           0.85      1500
   macro avg       0.65      0.52      0.51      1500
weighted avg       0.80      0.85      0.80      1500

[[1262   15]
 [ 211   12]]


# ANN

In [56]:

from sklearn.neural_network import MLPClassifier

ann = MLPClassifier(hidden_layer_sizes=(10,10,10), max_iter = 1000)
ann.fit(x_train,y_train.values.ravel())
y_pred = ann.predict(x_test)


# Compute confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print(" Artifical Neural Network ANN Output")

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Compute precision
precision = precision_score(y_test, y_pred)
print('Precision:', precision)

# Compute specificity
specificity = tn / (tn + fp)
print('Specificity:', specificity)

# Compute recall
recall = recall_score(y_test, y_pred)
print('Recall:', recall)

# Compute sensitivity
sensitivity= tp / (tp + fn)
print('Sensitivity:', sensitivity)

# Compute F1-score
f1 = f1_score(y_test, y_pred)
print('F1 Score:', f1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))


 Artifical Neural Network ANN Output
Accuracy: 0.8593333333333333
Precision: 0.65
Specificity: 0.9890368050117463
Recall: 0.11659192825112108
Sensitivity: 0.11659192825112108
F1 Score: 0.19771863117870725
              precision    recall  f1-score   support

         0.0       0.87      0.99      0.92      1277
         1.0       0.65      0.12      0.20       223

    accuracy                           0.86      1500
   macro avg       0.76      0.55      0.56      1500
weighted avg       0.83      0.86      0.82      1500

[[1263   14]
 [ 197   26]]
